### ISSUE TITLE
PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in fastbill-functions.php:776

### ISSUE THREAD

**Issue by flowdee** [drumba/edd-fastbill#6]
```
PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php:776
Stack trace:
#0 /public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php(776): SimpleXMLElement->__construct('Connection Erro...')
#1 /public/wp-content/plugins/edd-fastbill/includes/register-settings.php(225): drumba\EDD\FastBill\FastBill->templates_get()
#2 /public/wp-content/plugins/edd-fastbill/includes/register-settings.php(53): drubba_fb_get_invoice_templates()
#3 /public/wp-includes/class-wp-hook.php(298): drubba_fb_register_settings(Array)
#4 /public/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array)
#5 /public/wp-content/plugins/easy-digital-downloads/includes/admin/settings/register-settings.php(670): apply_filters('edd in /public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776
```

**Comment by flowdee** [comment]
Heute wieder ähnliches Problem auf allen Seiten aufgetreten:

```
Warning: SimpleXMLElement::__construct(): Entity: line 44: parser error : Opening and ending tag mismatch: link line 28 and head in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </head> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 88: parser error : xmlParseEntityRef: no name in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): if ((xingLoginArmed)&&(response.user)) { in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 88: parser error : xmlParseEntityRef: no name in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): if ((xingLoginArmed)&&(response.user)) { in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 180: parser error : Opening and ending tag mismatch: input line 180 and td in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): <input type="email" name="email" id="email" value="" class="email required"></td in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 181: parser error : Opening and ending tag mismatch: td line 180 and tr in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </tr> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 185: parser error : Opening and ending tag mismatch: input line 185 and td in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): put type="password" name="password" id="password" value="" class="required"></td in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 186: parser error : Opening and ending tag mismatch: td line 185 and tr in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </tr> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 224: parser error : Opening and ending tag mismatch: tr line 183 and table in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </table> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 228: parser error : Opening and ending tag mismatch: tr line 178 and form in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </form> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 235: parser error : Opening and ending tag mismatch: table line 155 and div in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </div> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 237: parser error : Opening and ending tag mismatch: input line 153 and div in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </div> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 238: parser error : Opening and ending tag mismatch: input line 152 and div in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </div> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 239: parser error : Opening and ending tag mismatch: form line 151 and div in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </div> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 243: parser error : Opening and ending tag mismatch: div line 141 and td in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </td> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 244: parser error : Opening and ending tag mismatch: div line 140 and tr in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </tr> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 245: parser error : Opening and ending tag mismatch: div line 139 and table in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </table> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 250: parser error : xmlParseEntityRef: no name in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): <a href="https://www.fastbill.com/impressum" target="_blank">Kontakt & I in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 266: parser error : Opening and ending tag mismatch: td line 136 and body in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): </body> in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): ^ in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Opening and ending tag mismatch: tr line 135 and html in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag table line 134 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag div line 132 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag body line 45 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag link line 27 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag link line 26 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag link line 25 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag link line 24 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag meta line 4 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag head line 3 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Warning: SimpleXMLElement::__construct(): Entity: line 267: parser error : Premature end of data in tag html line 2 in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776

Fatal error: Uncaught Exception: String could not be parsed as XML in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php:776 Stack trace: #0 /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php(776): SimpleXMLElement->__construct('<!DOCTYPE html>...') #1 /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/register-settings.php(225): drumba\EDD\FastBill\FastBill->templates_get() #2 /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/register-settings.php(53): drubba_fb_get_invoice_templates() #3 /srv/users/serverpilot/apps/my-site/public/wp-includes/class-wp-hook.php(298): drubba_fb_register_settings(Array) #4 /srv/users/serverpilot/apps/my-site/public/wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #5 /srv/users/serverpilot/apps/my-site/public/wp-cont in /srv/users/serverpilot/apps/my-site/public/wp-content/plugins/edd-fastbill/includes/fastbill-functions.php on line 776
```

Was komisch ist: Der Admin-Bereich ist anschließend nicht mehr aufrufbar (weiße Seite). Muss das Plugin deaktivieren, um reinzukommen. Selbst nach re-aktivieren, kommt wieder eine weiße Seite, als ob noch irgendwas "hängt". Hab die Templates mal aus den Transienten gelöscht, aber nix gebracht.

Werde hier Rückmeldung geben, wenn ich ne Lösung dafür gefunden habe.

**Comment by flowdee** [comment]
Update: Die Funktion templates_get gibt das HTML der Login-Seite zurück, weshalb das XML natürlich nicht _geparst_ werden kann.
